source "https://rubygems.org"

# to publish on github page
gem 'github-pages', group: :jekyll_plugins

# to publich without github page
#gem "kramdown-parser-gfm"
#gem "jekyll"

gem "webrick", "~> 1.7.0"
# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?