# .github/workflows/add-milestone.yml
name: Add Milestone
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v3
        if: |
          contains(github.event.pull_request.labels.*.name, 'content: article') ||
          contains(github.event.pull_request.labels.*.name, 'content: blog') ||
          contains(github.event.pull_request.labels.*.name, 'content: curated') ||
          contains(github.event.pull_request.labels.*.name, 'content: event') ||
          contains(github.event.pull_request.labels.*.name, 'content: howto') ||
          contains(github.event.pull_request.labels.*.name, 'content: updates') ||
          contains(github.event.pull_request.labels.*.name, 'content: whatis') ||
          contains(github.event.pull_request.labels.*.name, 'content: time sensitive') ||
          contains(github.event.pull_request.labels.*.name, 'content: article-deprecated') ||
          contains(github.event.pull_request.labels.*.name, 'content: howto-deprecated')
        with:
          # If true, add the milestone with the farthest due date. By default,
          # the action adds the current milestone (closest due date).
          farthest: false

          # If true, overwrite existing milestones on issues and pull requests.
          # By default, the action exits if a milestone has already been added.
          overwrite: false

          # If true, add the only open milestone in a repo, even if there is no
          # due date. By default, milestones with no due date are ignored.
          single: false
