name: Close Milestones
# This action will close past-due milestones with no open issues or PRs

on:
  pull_request:
    types: [closed]
  issues:
    types: [closed]
  workflow_dispatch:

jobs:
  close-milestone:
    name: Close Milestone
    runs-on: ubuntu-latest
    steps:
    - name: Run Close Milestone Action
      id: run-close-milestone-action
      uses: synergy-au/Close-Milestone-Action@v1.2
      with:
        secrets-token: ${{ secrets.GITHUB_TOKEN }}
